[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
drift = "MqL7XE1SYHin4i5yr2csyQGVcmcfCKXpzMZRk3BsJp4"
pyth = "JBdG99T7G1BkzwSPpB8AqfRLkiRweoWeRFCtpgQ4qvQ"
token_faucet = "BMkphy4BGXHkT8ftaTvFmzxQgCg4i6CmUZ7LnHpGW3hb"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "http://localhost:8899"
wallet = "/Users/gopalk/.config/solana/id.json"

[workspace]
exclude = ["programs/openbook_v2"]

[scripts]
fulltest = "cargo test && bash ./test-scripts/run-anchor-tests.sh"
lint = "yarn prettify:fix && cargo fmt"
test = "echo"
watch_build = "find ./programs/clearing_house/src/* ./tests ./sdk/src | entr -c anchor build"
watch_cargo = "find ./programs/clearing_house/src/* ./tests ./sdk/src | entr -c cargo test -- --show-output"
watch_ts = "find ./programs/clearing_house/src/* ./tests ./sdk/src | entr -c bash ./test-scripts/single-anchor-test.sh"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "0.0.0.0"
ledger = ".anchor/test-ledger"
rpc_port = 8899

[[test.validator.account]]
address = "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v"
filename = "./deps/configs/usdc.json"

[[test.validator.account]]
address = "3rdJbqfnagQ4yx9HXJViD4zc4xpiSqmFsKpPuSCQVyQL"
filename = "./deps/configs/pyth_lazer_storage.json"
